module.exports = {
  darkMode: "class",
  content: ["./public/**/*.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [
    "border-blue-500",
    "border-green-500",
    "border-yellow-500",
    "border-purple-500",
    "text-blue-400",
    "text-green-400",
    "text-yellow-400",
    "text-purple-400",
    "text-blue-500",
    "text-green-500",
    "text-yellow-500",
    "text-purple-500",
    "text-blue-600",
    "text-green-600",
    "text-yellow-600",
    "text-purple-600",
  ],
};